version: '3.8'

services:
  schema_registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema_registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: "schema_registry"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    networks:
      - kafka-net

networks:
  kafka-net:
    name: kafka-net
    external: true