version: '3.8'

services:
  stream_processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream_processor
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SPRING_STREAM_APPLICATION=${SPRING_STREAM_APPLICATION}
      - SPRING_KAFKA_SERVERS=${SPRING_KAFKA_SERVERS}
      - SPRING_SCHEMA_REGISTRY_URL=${SPRING_SCHEMA_REGISTRY_URL}
      - SPRING_SPECIFIC_AVRO_READER=${SPRING_SPECIFIC_AVRO_READER}
      - STREAM_VEHICLE_EVENT_AVRO_TOPIC=${STREAM_VEHICLE_EVENT_AVRO_TOPIC}
      - STREAM_VEHICLE_METADATA_AVRO_TOPIC=${STREAM_VEHICLE_METADATA_AVRO_TOPIC}
      - STREAM_VEHICLE_SPEEDING_AVRO_TOPIC=${STREAM_VEHICLE_SPEEDING_AVRO_TOPIC}
      - STREAM_VEHICLE_BRAKING_AVRO_TOPIC=${STREAM_VEHICLE_BRAKING_AVRO_TOPIC}
      - STREAM_VEHICLE_IDLE_AVRO_TOPIC=${STREAM_VEHICLE_IDLE_AVRO_TOPIC}
      - STREAM_VEHICLE_ENRICHED_AVRO_TOPIC=${STREAM_VEHICLE_ENRICHED_AVRO_TOPIC}
    networks:
      - kafka-net

networks:
  kafka-net:
    name: kafka-net
    external: true